KEYWORD_MAPPING = {

    # ─────────────────────────────────────────────
    # INTERNSHIPS & APPRENTICESHIPS
    # ─────────────────────────────────────────────
    "stagiaire": "Internships",
    "stagaire": "Internships",
    "stage": "Internships",
    "apprenti": "Internships",
    "apprentie": "Internships",

    # ─────────────────────────────────────────────
    # IT DEVELOPMENT
    # ─────────────────────────────────────────────
    "developpeur": "IT Development",
    "developpeuse": "IT Development",
    "developeur": "IT Development",
    "programmeur": "IT Development",
    "full stack": "IT Development",
    "fullstack": "IT Development",
    "full-stack": "IT Development",
    "front end": "IT Development",
    "frontend": "IT Development",
    "back end": "IT Development",
    "backend": "IT Development",
    "react js": "IT Development",
    "react native": "IT Development",
    "react angular": "IT Development",
    "angular": "IT Development",
    "angularionic": "IT Development",
    "node js": "IT Development",
    "nodejs": "IT Development",
    "next js": "IT Development",
    "nextjs": "IT Development",
    "vuejs": "IT Development",
    "vue js": "IT Development",
    "typescript": "IT Development",
    "javascript": "IT Development",
    "php": "IT Development",
    "phpsymfony": "IT Development",
    "phplaravel": "IT Development",
    "symfony": "IT Development",
    "laravel": "IT Development",
    "python": "IT Development",
    "pythonodoo": "IT Development",
    "django": "IT Development",
    "fast api": "IT Development",
    "java": "IT Development",
    "javaphp": "IT Development",
    "javaspark": "IT Development",
    "javakotlin": "IT Development",
    "javaangular": "IT Development",
    "kotlin": "IT Development",
    "golang": "IT Development",
    "ruby": "IT Development",
    "net angular": "IT Development",
    "dotnet": "IT Development",
    "flutter": "IT Development",
    "flutterflow": "IT Development",
    "flutter flow": "IT Development",
    "mobile developer": "IT Development",
    "mobile developers": "IT Development",
    "application mobile": "IT Development",
    "app mobile": "IT Development",
    "dapplication mobile": "IT Development",
    "dapplications": "IT Development",
    "dapplications smartphone": "IT Development",
    "mern stack": "IT Development",
    "mean stack": "IT Development",
    "wordpress": "IT Development",
    "prestashop": "IT Development",
    "shopify": "IT Development",
    "magento": "IT Development",
    "webflow": "IT Development",
    "drupal": "IT Development",
    "odoo": "IT Development",
    "win dev": "IT Development",
    "windev": "IT Development",
    "zoho": "IT Development",
    "salesforce": "IT Development",
    "sharepoint": "IT Development",
    "dynamics": "IT Development",
    "powerapps": "IT Development",
    "sap": "IT Development",
    "sap abap": "IT Development",
    "sap developper": "IT Development",
    "filemaker": "IT Development",
    "talend": "IT Development",
    "webmaster": "IT Development",
    "webmobile": "IT Development",
    "web designer": "IT Development",
    "aws developer": "IT Development",
    "aws engineer": "IT Development",
    "lead full stack": "IT Development",
    "lead tech react": "IT Development",
    "lead typescript": "IT Development",
    "lead developpeur": "IT Development",
    "jior developper": "IT Development",
    "ingenieur docker": "IT Development",
    "ingenieur net": "IT Development",
    "ingenieur java": "IT Development",
    "ingenieur javakotlin": "IT Development",
    "ingenieur applicatif": "IT Development",
    "ingenieur informatique": "IT Development",
    "ingenieur devops": "IT Development",
    "ingenieur big data": "IT Development",
    "linux embarque": "IT Development",
    "plsql": "IT Development",
    "cms": "IT Development",
    "logiciel": "IT Development",
    "applications developpements": "IT Development",
    "application developpement odoo": "IT Development",
    "applicatif": "IT Development",

    # ─────────────────────────────────────────────
    # DATA & AI
    # ─────────────────────────────────────────────
    "data analyst": "Data & AI",
    "data scientist": "Data & AI",
    "data scientiste": "Data & AI",
    "data engineer": "Data & AI",
    "data miner": "Data & AI",
    "data warehouse": "Data & AI",
    "data administrator": "Data & AI",
    "data prospector": "Data & AI",
    "data center operations": "Data & AI",
    "devdata engineer": "Data & AI",
    "intelligence artificielle": "Data & AI",
    "ia": "Data & AI",
    "machine learning": "Data & AI",
    "ingenieur iaml": "Data & AI",
    "ingenieur data": "Data & AI",
    "ingenieur bi": "Data & AI",
    "ingenieur big data ops": "Data & AI",
    "power bi": "Data & AI",
    "business intelligence": "Data & AI",
    "analyste algo": "Data & AI",
    "analyste fonctionnel bi": "Data & AI",
    "analyste financier bi": "Data & AI",
    "analyste talend": "Data & AI",
    "analyst idp": "Data & AI",
    "annotateur": "Data & AI",
    "annotateurs": "Data & AI",
    "data labeler": "Data & AI",
    "data configuration": "Data & AI",
    "extraction donnees": "Data & AI",
    "modelisation developpement": "Data & AI",

    # ─────────────────────────────────────────────
    # DEVOPS / SYSADMIN / NETWORKS
    # ─────────────────────────────────────────────
    "devops": "DevOps & Infrastructure",
    "ingenieur devops cloud": "DevOps & Infrastructure",
    "administrateur systeme": "DevOps & Infrastructure",
    "administrateur systemes": "DevOps & Infrastructure",
    "administrateur reseaux": "DevOps & Infrastructure",
    "administrateur reseau": "DevOps & Infrastructure",
    "administrateur linux": "DevOps & Infrastructure",
    "administrateur office azure": "DevOps & Infrastructure",
    "administrateur independant": "DevOps & Infrastructure",
    "administrateur wordkay": "DevOps & Infrastructure",
    "administrateur erp": "DevOps & Infrastructure",
    "administration reseau": "DevOps & Infrastructure",
    "administration reseaux": "DevOps & Infrastructure",
    "administration base donnees": "DevOps & Infrastructure",
    "administrateur systeme linux": "DevOps & Infrastructure",
    "administrateur linux": "DevOps & Infrastructure",
    "it administrateur": "DevOps & Infrastructure",
    "it analyst": "DevOps & Infrastructure",
    "it system administrator": "DevOps & Infrastructure",
    "informatique suivi": "DevOps & Infrastructure",
    "informaticien maintenance": "DevOps & Infrastructure",
    "informaticien gestion": "DevOps & Infrastructure",
    "informaticien phpsymfony": "DevOps & Infrastructure",
    "informaticien": "DevOps & Infrastructure",
    "informaticien audit": "DevOps & Infrastructure",
    "reseaux systemes": "DevOps & Infrastructure",
    "reseaux systeme": "DevOps & Infrastructure",
    "reseau": "DevOps & Infrastructure",
    "reseaux it": "DevOps & Infrastructure",
    "reseaux physiques": "DevOps & Infrastructure",
    "reseaux magasins": "DevOps & Infrastructure",
    "network engineer": "DevOps & Infrastructure",
    "core network engineer": "DevOps & Infrastructure",
    "ip engineer": "DevOps & Infrastructure",
    "microwave engineer": "DevOps & Infrastructure",
    "ingenieur reseaux": "DevOps & Infrastructure",
    "ingenieur systemes reseaux": "DevOps & Infrastructure",
    "offre systemes reseaux": "DevOps & Infrastructure",
    "architecte systemes": "DevOps & Infrastructure",
    "architecte logiciel": "DevOps & Infrastructure",
    "infrastructure it": "DevOps & Infrastructure",
    "infrastructure": "DevOps & Infrastructure",
    "deploiement it": "DevOps & Infrastructure",
    "gestionnaire parc informatique": "DevOps & Infrastructure",
    "gestionnaire reseau informatique": "DevOps & Infrastructure",
    "poste travail": "DevOps & Infrastructure",
    "securite informatique": "DevOps & Infrastructure",
    "securite systemes": "DevOps & Infrastructure",
    "ingenieur securite informatique": "DevOps & Infrastructure",
    "rssi": "DevOps & Infrastructure",
    "cybersecurity": "DevOps & Infrastructure",
    "cloud": "DevOps & Infrastructure",
    "aws": "DevOps & Infrastructure",

    # ─────────────────────────────────────────────
    # DESIGN & DIGITAL CONTENT
    # ─────────────────────────────────────────────
    "graphiste": "Design & Digital Content",
    "infographiste": "Design & Digital Content",
    "infographistephotographe": "Design & Digital Content",
    "designer": "Design & Digital Content",
    "ui ux": "Design & Digital Content",
    "ux ui": "Design & Digital Content",
    "uiux": "Design & Digital Content",
    "uxui": "Design & Digital Content",
    "ux mobile": "Design & Digital Content",
    "motion": "Design & Digital Content",
    "directeur artistique": "Design & Digital Content",
    "directeur artistique specialise motion": "Design & Digital Content",
    "visual content creator": "Design & Digital Content",
    "createur contenu": "Design & Digital Content",
    "createurcreatrice contenus": "Design & Digital Content",
    "monteur youtube": "Design & Digital Content",
    "modeleur bim": "Design & Digital Content",
    "modeleur talentueux": "Design & Digital Content",
    "modeliste": "Design & Digital Content",
    "illustrateur": "Design & Digital Content",
    "relume figma": "Design & Digital Content",
    "figma": "Design & Digital Content",
    "community management": "Design & Digital Content",
    "community manager": "Design & Digital Content",
    "commity": "Design & Digital Content",
    "gestionnaire reseaux sociaux": "Design & Digital Content",
    "operateur reseaux sociaux": "Design & Digital Content",
    "content": "Design & Digital Content",
    "gestionnaire contenu": "Design & Digital Content",
    "digital content editor": "Design & Digital Content",
    "moderateur contenu": "Design & Digital Content",
    "moderateur": "Design & Digital Content",
    "stagiaireapprenti media": "Design & Digital Content",
    "editeur contenus": "Design & Digital Content",

    # ─────────────────────────────────────────────
    # DIGITAL MARKETING & E-COMMERCE
    # ─────────────────────────────────────────────
    "webmarketing": "Digital Marketing & E-Commerce",
    "webmarketer": "Digital Marketing & E-Commerce",
    "stratege marketing numerique": "Digital Marketing & E-Commerce",
    "marketing digital": "Digital Marketing & E-Commerce",
    "growth marketing": "Digital Marketing & E-Commerce",
    "growth marketer": "Digital Marketing & E-Commerce",
    "growth hacker": "Digital Marketing & E-Commerce",
    "seo": "Digital Marketing & E-Commerce",
    "sea": "Digital Marketing & E-Commerce",
    "sem": "Digital Marketing & E-Commerce",
    "traffic manager": "Digital Marketing & E-Commerce",
    "traffic franco": "Digital Marketing & E-Commerce",
    "emailing": "Digital Marketing & E-Commerce",
    "social media": "Digital Marketing & E-Commerce",
    "e-commerce": "Digital Marketing & E-Commerce",
    "ecommerce": "Digital Marketing & E-Commerce",
    "facebook ads": "Digital Marketing & E-Commerce",
    "google ads": "Digital Marketing & E-Commerce",
    "expert ads": "Digital Marketing & E-Commerce",
    "ads": "Digital Marketing & E-Commerce",
    "media buyer": "Digital Marketing & E-Commerce",
    "affiliate": "Digital Marketing & E-Commerce",
    "expert affiliate": "Digital Marketing & E-Commerce",
    "fidelisation crm": "Digital Marketing & E-Commerce",
    "shopify growth": "Digital Marketing & E-Commerce",
    "amazon": "Digital Marketing & E-Commerce",
    "leadflow": "Digital Marketing & E-Commerce",
    "generation leads": "Digital Marketing & E-Commerce",
    "prospection email": "Digital Marketing & E-Commerce",
    "lancement produit": "Digital Marketing & E-Commerce",
    "gestionnaire campagnes": "Digital Marketing & E-Commerce",
    "marche contenu": "Digital Marketing & E-Commerce",

    # ─────────────────────────────────────────────
    # SALES & TELEPROSPECTING
    # ─────────────────────────────────────────────
    "tele prospecteur": "Sales & Teleprospecting",
    "teleprospecteur": "Sales & Teleprospecting",
    "tele propsecteur": "Sales & Teleprospecting",
    "teleprospectrice": "Sales & Teleprospecting",
    "prospecteur": "Sales & Teleprospecting",
    "prospectrice": "Sales & Teleprospecting",
    "prospection": "Sales & Teleprospecting",
    "sdr": "Sales & Teleprospecting",
    "setter": "Sales & Teleprospecting",
    "setteur": "Sales & Teleprospecting",
    "closer": "Sales & Teleprospecting",
    "vendeur": "Sales & Teleprospecting",
    "vendeuse": "Sales & Teleprospecting",
    "vendeurs": "Sales & Teleprospecting",
    "commercial": "Sales & Teleprospecting",
    "commerciaux": "Sales & Teleprospecting",
    "commerciale": "Sales & Teleprospecting",
    "technico commercial": "Sales & Teleprospecting",
    "technico": "Sales & Teleprospecting",
    "conseiller commercial": "Sales & Teleprospecting",
    "conseillers commerciaux": "Sales & Teleprospecting",
    "sales representative": "Sales & Teleprospecting",
    "sales development representative": "Sales & Teleprospecting",
    "sales engineer": "Sales & Teleprospecting",
    "sales expert": "Sales & Teleprospecting",
    "sales": "Sales & Teleprospecting",
    "inside sales": "Sales & Teleprospecting",
    "ingenieur avant vente": "Sales & Teleprospecting",
    "avant vente": "Sales & Teleprospecting",
    "business development": "Sales & Teleprospecting",
    "business developper": "Sales & Teleprospecting",
    "developpement business": "Sales & Teleprospecting",
    "prise rendez": "Sales & Teleprospecting",
    "prise rdv": "Sales & Teleprospecting",
    "appel sortant": "Sales & Teleprospecting",
    "operateur prise rdv": "Sales & Teleprospecting",
    "operateur vente": "Sales & Teleprospecting",
    "agents tele": "Sales & Teleprospecting",
    "demarcheur": "Sales & Teleprospecting",
    "promoteur ventes": "Sales & Teleprospecting",
    "animatrice vente": "Sales & Teleprospecting",
    "animateur ventes": "Sales & Teleprospecting",
    "animatrices vente": "Sales & Teleprospecting",
    "agent commercial": "Sales & Teleprospecting",
    "representante commerciale": "Sales & Teleprospecting",
    "auxiliaire vente": "Sales & Teleprospecting",
    "vente": "Sales & Teleprospecting",
    "ventes": "Sales & Teleprospecting",
    "previsionniste ventes": "Sales & Teleprospecting",
    "administration ventes": "Sales & Teleprospecting",
    "administration vente": "Sales & Teleprospecting",
    "adv administration ventes": "Sales & Teleprospecting",
    "administrateur ventes": "Sales & Teleprospecting",
    "ladministrateur ventes": "Sales & Teleprospecting",
    "administrateur vente": "Sales & Teleprospecting",
    "grands comptes": "Sales & Teleprospecting",
    "key accot": "Sales & Teleprospecting",
    "chief sales officer": "Sales & Teleprospecting",
    "head of traditional sales": "Sales & Teleprospecting",
    "traditional sales department": "Sales & Teleprospecting",
    "real estate business development": "Sales & Teleprospecting",
    "societe immobiliere": "Sales & Teleprospecting",

    # ─────────────────────────────────────────────
    # CUSTOMER SERVICE & CALL CENTER
    # ─────────────────────────────────────────────
    "call center": "Customer Service & Call Center",
    "call centre": "Customer Service & Call Center",
    "call": "Customer Service & Call Center",
    "call officer": "Customer Service & Call Center",
    "call sup": "Customer Service & Call Center",
    "chat operators": "Customer Service & Call Center",
    "conseiller client": "Customer Service & Call Center",
    "conseillers clients": "Customer Service & Call Center",
    "conseiller clientele": "Customer Service & Call Center",
    "gestionnaire clientele": "Customer Service & Call Center",
    "superviseur dequipe service client": "Customer Service & Call Center",
    "superviseurs dequipe service client": "Customer Service & Call Center",
    "supports clients": "Customer Service & Call Center",
    "support client": "Customer Service & Call Center",
    "agents supports clients": "Customer Service & Call Center",
    "service client": "Customer Service & Call Center",
    "service desk": "Customer Service & Call Center",
    "customer care": "Customer Service & Call Center",
    "customer success": "Customer Service & Call Center",
    "customer service": "Customer Service & Call Center",
    "customer experiences": "Customer Service & Call Center",
    "customer satisfaction": "Customer Service & Call Center",
    "customer tech specialist": "Customer Service & Call Center",
    "customer english": "Customer Service & Call Center",
    "english customer advisors": "Customer Service & Call Center",
    "english speaking customer service": "Customer Service & Call Center",
    "client multilingue": "Customer Service & Call Center",
    "client presentiel": "Customer Service & Call Center",
    "gestionnaire relation client": "Customer Service & Call Center",
    "relation client": "Customer Service & Call Center",
    "relation clients": "Customer Service & Call Center",
    "crc": "Customer Service & Call Center",
    "outsourcer specialist": "Customer Service & Call Center",
    "operateur ecoute": "Customer Service & Call Center",
    "operateur anglophone": "Customer Service & Call Center",
    "operateur germanophone": "Customer Service & Call Center",
    "operateur back": "Customer Service & Call Center",
    "operateur back office": "Customer Service & Call Center",
    "operateur bpo": "Customer Service & Call Center",

    # ─────────────────────────────────────────────
    # SUPERVISION & MANAGEMENT
    # ─────────────────────────────────────────────
    "superviseur": "Supervision & Management",
    "team leader": "Supervision & Management",
    "team lead": "Supervision & Management",
    "responsable": "Supervision & Management",
    "directeur": "Supervision & Management",
    "directeurtrice": "Supervision & Management",
    "directeurrice": "Supervision & Management",
    "directrice": "Supervision & Management",
    "manager": "Supervision & Management",
    "head of": "Supervision & Management",
    "chef": "Supervision & Management",
    "chef de projet": "Supervision & Management",
    "chef de chantier": "Supervision & Management",
    "chef de production": "Supervision & Management",
    "chef de service": "Supervision & Management",
    "coordinateur": "Supervision & Management",
    "coordonnateur": "Supervision & Management",
    "coordonateur": "Supervision & Management",
    "cadre": "Supervision & Management",
    "dop": "Supervision & Management",
    "pmo": "Supervision & Management",
    "project manager": "Supervision & Management",
    "project management officer": "Supervision & Management",
    "product owner": "Supervision & Management",
    "monetics product owner": "Supervision & Management",
    "directeur general": "Supervision & Management",
    "chief finance officer": "Supervision & Management",
    "chief sales officer": "Supervision & Management",
    "bras droit ceo": "Supervision & Management",

    # ─────────────────────────────────────────────
    # HR & RECRUITMENT
    # ─────────────────────────────────────────────
    "recruteur": "HR & Recruitment",
    "recrutement": "HR & Recruitment",
    "recrutment officer": "HR & Recruitment",
    "recruitment officer": "HR & Recruitment",
    "talent acquisition": "HR & Recruitment",
    "talent acquisition specialist": "HR & Recruitment",
    "chasseur talents": "HR & Recruitment",
    "chasseur de talents": "HR & Recruitment",
    "sourceur recrutement": "HR & Recruitment",
    "sourcing qualification cv": "HR & Recruitment",
    "rh": "HR & Recruitment",
    "ressources humaines": "HR & Recruitment",
    "developpement ressources humaines": "HR & Recruitment",
    "human resources": "HR & Recruitment",
    "human resources officer": "HR & Recruitment",
    "human ressource": "HR & Recruitment",
    "hrbp": "HR & Recruitment",
    "hr officer": "HR & Recruitment",
    "hr lead": "HR & Recruitment",
    "hr jior": "HR & Recruitment",
    "hr business partner": "HR & Recruitment",
    "human resource business partner": "HR & Recruitment",
    "human resources business partner": "HR & Recruitment",
    "interim rrh": "HR & Recruitment",
    "gestionnaire ressources humaines": "HR & Recruitment",
    "gestionnaire administration personnel": "HR & Recruitment",
    "gestionnaire recrutement": "HR & Recruitment",
    "standardiste": "HR & Recruitment",
    "standardistes bilingues": "HR & Recruitment",
    "payroll": "HR & Recruitment",
    "gestionnaire paye": "HR & Recruitment",
    "receptionniste": "HR & Recruitment",
    "receptioniste": "HR & Recruitment",
    "receptionist": "HR & Recruitment",

    # ─────────────────────────────────────────────
    # FINANCE & ACCOUNTING
    # ─────────────────────────────────────────────
    "comptable": "Finance & Accounting",
    "comptables": "Finance & Accounting",
    "collaborateur comptable": "Finance & Accounting",
    "collaborateurs comptables": "Finance & Accounting",
    "comptabilite": "Finance & Accounting",
    "comptabilite finance": "Finance & Accounting",
    "comptabilite francaise": "Finance & Accounting",
    "tresorier": "Finance & Accounting",
    "tresorerie": "Finance & Accounting",
    "controle de gestion": "Finance & Accounting",
    "controleur gestion": "Finance & Accounting",
    "controleur financier": "Finance & Accounting",
    "controleur interne": "Finance & Accounting",
    "controleur permanent": "Finance & Accounting",
    "controle financier": "Finance & Accounting",
    "controle gestion": "Finance & Accounting",
    "controle credit": "Finance & Accounting",
    "controle permanent": "Finance & Accounting",
    "facturation": "Finance & Accounting",
    "facturier": "Finance & Accounting",
    "paie": "Finance & Accounting",
    "finance": "Finance & Accounting",
    "financier": "Finance & Accounting",
    "pilotage financier": "Finance & Accounting",
    "consolidation financiere": "Finance & Accounting",
    "reporting financial controller": "Finance & Accounting",
    "financial planning": "Finance & Accounting",
    "financial controler": "Finance & Accounting",
    "daf": "Finance & Accounting",
    "daf adjoint": "Finance & Accounting",
    "analystes financiers": "Finance & Accounting",
    "analyste tresorerie": "Finance & Accounting",
    "analyste risque credit": "Finance & Accounting",
    "credit": "Finance & Accounting",
    "credit micro finance": "Finance & Accounting",
    "analyste credit": "Finance & Accounting",
    "recouvrement": "Finance & Accounting",
    "revenue assurance": "Finance & Accounting",
    "rapprochement bancaire": "Finance & Accounting",
    "bilan": "Finance & Accounting",
    "budget reporting": "Finance & Accounting",
    "fiscalite": "Finance & Accounting",
    "fiscaliste": "Finance & Accounting",
    "tax": "Finance & Accounting",
    "general ledger": "Finance & Accounting",
    "bilingual accotant": "Finance & Accounting",
    "accotant": "Finance & Accounting",
    "accot": "Finance & Accounting",
    "investment analyst": "Finance & Accounting",
    "gestionnaire encaissements": "Finance & Accounting",
    "gestionnaire paiements": "Finance & Accounting",
    "gestionnaire operations tresorerie": "Finance & Accounting",
    "gestionnaire immobilisations": "Finance & Accounting",
    "risques liquidite credit": "Finance & Accounting",
    "fraude risques": "Finance & Accounting",
    "managercomptable": "Finance & Accounting",
    "reviseurs comptables": "Finance & Accounting",
    "dossiers comptables": "Finance & Accounting",
    "si metier finance": "Finance & Accounting",
    "consolidation financiere": "Finance & Accounting",
    "lean management reporting": "Finance & Accounting",
    "management reporting analyst": "Finance & Accounting",

    # ─────────────────────────────────────────────
    # AUDIT & COMPLIANCE
    # ─────────────────────────────────────────────
    "auditeur": "Audit & Compliance",
    "auditeurs": "Audit & Compliance",
    "audit": "Audit & Compliance",
    "internal audit": "Audit & Compliance",
    "auditeur interne": "Audit & Compliance",
    "auditeur interne confirme": "Audit & Compliance",
    "conformite": "Audit & Compliance",
    "conformite systeme": "Audit & Compliance",
    "conformite groupe": "Audit & Compliance",
    "controle interne": "Audit & Compliance",
    "offre controle interne": "Audit & Compliance",
    "governance risk compliance": "Audit & Compliance",
    "qhse": "Audit & Compliance",
    "qhserse": "Audit & Compliance",
    "qhygiene securite": "Audit & Compliance",
    "hygiene securite environnement": "Audit & Compliance",
    "hygiene securite environnements": "Audit & Compliance",
    "hsse": "Audit & Compliance",
    "hse": "Audit & Compliance",
    "hse rhse": "Audit & Compliance",
    "suivi evaluation": "Audit & Compliance",
    "gestionnaire appels doffre": "Audit & Compliance",
    "appel doffres": "Audit & Compliance",

    # ─────────────────────────────────────────────
    # ERP / FUNCTIONAL CONSULTING
    # ─────────────────────────────────────────────
    "consultant fonctionnel": "ERP & Functional Consulting",
    "consultant erp": "ERP & Functional Consulting",
    "consultant fonctionnel odoo": "ERP & Functional Consulting",
    "consultant fonctionnel crm": "ERP & Functional Consulting",
    "consultant fonctionnel sage": "ERP & Functional Consulting",
    "consultant si": "ERP & Functional Consulting",
    "consultant data bi": "ERP & Functional Consulting",
    "consultant bi": "ERP & Functional Consulting",
    "consultant applicatif": "ERP & Functional Consulting",
    "consultante technique sage": "ERP & Functional Consulting",
    "consultante fonctionnelle sage": "ERP & Functional Consulting",
    "consultant dba": "ERP & Functional Consulting",
    "consultant architecte solutions": "ERP & Functional Consulting",
    "analyste fonctionnel": "ERP & Functional Consulting",
    "analyste fonctionnel odoo": "ERP & Functional Consulting",
    "fonctionnel erp": "ERP & Functional Consulting",
    "integrateur": "ERP & Functional Consulting",
    "integrateur odoo": "ERP & Functional Consulting",
    "integrateur prestashop": "ERP & Functional Consulting",
    "integrateur solutions saas": "ERP & Functional Consulting",
    "integrateur migration contenu": "ERP & Functional Consulting",
    "integrateur experimente": "ERP & Functional Consulting",
    "gestionnaire erp": "ERP & Functional Consulting",
    "erp": "ERP & Functional Consulting",
    "odoo project": "ERP & Functional Consulting",
    "confirmes odoo": "ERP & Functional Consulting",
    "developpeurs odoo": "ERP & Functional Consulting",
    "experte odoo": "ERP & Functional Consulting",
    "sage": "ERP & Functional Consulting",
    "automatisation integration saas": "ERP & Functional Consulting",
    "specialist integration api": "ERP & Functional Consulting",
    "laravel integration api": "ERP & Functional Consulting",
    "business analyst odoo": "ERP & Functional Consulting",
    "business analyst it": "ERP & Functional Consulting",
    "business analyst expert": "ERP & Functional Consulting",
    "business analyst": "ERP & Functional Consulting",
    "business process analyst": "ERP & Functional Consulting",
    "process analyst": "ERP & Functional Consulting",
    "business resilience": "ERP & Functional Consulting",
    "business efficience": "ERP & Functional Consulting",
    "consultant expert zabbix": "ERP & Functional Consulting",

    # ─────────────────────────────────────────────
    # LOGISTICS & SUPPLY CHAIN
    # ─────────────────────────────────────────────
    "logistique": "Logistics & Supply Chain",
    "logisticien": "Logistics & Supply Chain",
    "transit": "Logistics & Supply Chain",
    "supply chain": "Logistics & Supply Chain",
    "magasinier": "Logistics & Supply Chain",
    "stock": "Logistics & Supply Chain",
    "stocks": "Logistics & Supply Chain",
    "transport": "Logistics & Supply Chain",
    "livreur": "Logistics & Supply Chain",
    "chauffeur livreur": "Logistics & Supply Chain",
    "chauffeur": "Logistics & Supply Chain",
    "chauffeurs": "Logistics & Supply Chain",
    "conducteur": "Logistics & Supply Chain",
    "conducteur moto": "Logistics & Supply Chain",
    "conducteur engins": "Logistics & Supply Chain",
    "coursier": "Logistics & Supply Chain",
    "coursier livreur": "Logistics & Supply Chain",
    "dispatcher": "Logistics & Supply Chain",
    "planificateur livraison": "Logistics & Supply Chain",
    "planificateur": "Logistics & Supply Chain",
    "planning": "Logistics & Supply Chain",
    "planification": "Logistics & Supply Chain",
    "cariste": "Logistics & Supply Chain",
    "conducteur chariot elevateur": "Logistics & Supply Chain",
    "magasin": "Logistics & Supply Chain",
    "magasin pieces detachees": "Logistics & Supply Chain",
    "magasin pieces rechange": "Logistics & Supply Chain",
    "depot": "Logistics & Supply Chain",
    "reception livraisons": "Logistics & Supply Chain",
    "receptionnaire": "Logistics & Supply Chain",
    "approvisionnement": "Logistics & Supply Chain",
    "approvisionnements": "Logistics & Supply Chain",
    "approvisionneur": "Logistics & Supply Chain",
    "approvisionnement textile": "Logistics & Supply Chain",
    "achat": "Logistics & Supply Chain",
    "achats": "Logistics & Supply Chain",
    "acheteur": "Logistics & Supply Chain",
    "acheteurs": "Logistics & Supply Chain",
    "achats techniques logistiques": "Logistics & Supply Chain",
    "achats internationaux": "Logistics & Supply Chain",
    "achats approvisionnements": "Logistics & Supply Chain",
    "demand planner": "Logistics & Supply Chain",
    "gestionnaire dentrepot": "Logistics & Supply Chain",
    "gestionnaire approvisionnement": "Logistics & Supply Chain",
    "gestionnaire flotte": "Logistics & Supply Chain",
    "gestionnaire flotte location": "Logistics & Supply Chain",
    "gestionnaire import export": "Logistics & Supply Chain",
    "importation": "Logistics & Supply Chain",
    "expedition": "Logistics & Supply Chain",
    "shipping": "Logistics & Supply Chain",
    "international freight forwarding": "Logistics & Supply Chain",
    "operatuer suivie flotte": "Logistics & Supply Chain",
    "operateur suivi flotte": "Logistics & Supply Chain",
    "operateur surveillance": "Logistics & Supply Chain",
    "flotte": "Logistics & Supply Chain",
    "parc auto": "Logistics & Supply Chain",
    "parc automobile": "Logistics & Supply Chain",
    "sourcing relations fournisseurs": "Logistics & Supply Chain",
    "reglement fournisseur": "Logistics & Supply Chain",
    "commissionnaire": "Logistics & Supply Chain",
    "consignation maritime": "Logistics & Supply Chain",
    "fleet supervisor": "Logistics & Supply Chain",

    # ─────────────────────────────────────────────
    # ADMINISTRATION & SECRETARIAL
    # ─────────────────────────────────────────────
    "secretaire": "Administration & Secretarial",
    "administratif": "Administration & Secretarial",
    "administrateur": "Administration & Secretarial",
    "admin officer": "Administration & Secretarial",
    "back office": "Administration & Secretarial",
    "assistante": "Administration & Secretarial",
    "assistant": "Administration & Secretarial",
    "assistance direction": "Administration & Secretarial",
    "adjointe administrative": "Administration & Secretarial",
    "adjoint direction": "Administration & Secretarial",
    "office": "Administration & Secretarial",
    "office facility": "Administration & Secretarial",
    "service generaux": "Administration & Secretarial",
    "moyens generaux": "Administration & Secretarial",
    "moyens generaux": "Administration & Secretarial",
    "moyen genereaux": "Administration & Secretarial",
    "economat": "Administration & Secretarial",
    "gestion base donnees": "Administration & Secretarial",
    "saisie donnees": "Administration & Secretarial",
    "operateur saisie": "Administration & Secretarial",
    "operateur operatrice saisie": "Administration & Secretarial",
    "operateur back": "Administration & Secretarial",
    "legal officer": "Administration & Secretarial",
    "affaires juridiques": "Administration & Secretarial",
    "juridique": "Administration & Secretarial",
    "juriste": "Administration & Secretarial",
    "avocat": "Administration & Secretarial",
    "conseiller juridique": "Administration & Secretarial",
    "consultant juridique": "Administration & Secretarial",
    "corporate dossiers": "Administration & Secretarial",
    "gestion projet immobilier": "Administration & Secretarial",
    "dossiers comptables": "Administration & Secretarial",

    # ─────────────────────────────────────────────
    # TECHNICAL TRADES & ENGINEERING
    # ─────────────────────────────────────────────
    "technicien maintenance": "Technical Trades & Engineering",
    "technicien solaire": "Technical Trades & Engineering",
    "technicien frigoriste": "Technical Trades & Engineering",
    "technicien btp": "Technical Trades & Engineering",
    "frigoriste": "Technical Trades & Engineering",
    "electricien": "Technical Trades & Engineering",
    "electricite": "Technical Trades & Engineering",
    "electricite industrielle": "Technical Trades & Engineering",
    "electricite electronique": "Technical Trades & Engineering",
    "electromecanicien": "Technical Trades & Engineering",
    "electronicien": "Technical Trades & Engineering",
    "electrotechnicien": "Technical Trades & Engineering",
    "ingenieur genie electrique": "Technical Trades & Engineering",
    "ingenieur electromecanicien": "Technical Trades & Engineering",
    "ingenieur electronique firmware": "Technical Trades & Engineering",
    "ingenieur energie solaire": "Technical Trades & Engineering",
    "ingenieur installations solaires": "Technical Trades & Engineering",
    "ingenieur solaire": "Technical Trades & Engineering",
    "ingenieur fluide": "Technical Trades & Engineering",
    "ingenieur structure": "Technical Trades & Engineering",
    "ingenieur structure btp": "Technical Trades & Engineering",
    "ingenieur civil": "Technical Trades & Engineering",
    "ingenieur btp": "Technical Trades & Engineering",
    "ingenieur maintenance": "Technical Trades & Engineering",
    "ingenieur methode": "Technical Trades & Engineering",
    "ingenieur industriel": "Technical Trades & Engineering",
    "ingenieur production": "Technical Trades & Engineering",
    "ingenieur ouvrages dart": "Technical Trades & Engineering",
    "ingenieur hydraulique": "Technical Trades & Engineering",
    "ingenieur travaux publics": "Technical Trades & Engineering",
    "ingenieur construction": "Technical Trades & Engineering",
    "topographe": "Technical Trades & Engineering",
    "topographes": "Technical Trades & Engineering",
    "soudeur": "Technical Trades & Engineering",
    "plombier": "Technical Trades & Engineering",
    "plombier polyvalent": "Technical Trades & Engineering",
    "menuisier": "Technical Trades & Engineering",
    "charpentier": "Technical Trades & Engineering",
    "maon": "Technical Trades & Engineering",
    "maons": "Technical Trades & Engineering",
    "peintre": "Technical Trades & Engineering",
    "mecanicien": "Technical Trades & Engineering",
    "mecanicien automobile": "Technical Trades & Engineering",
    "mecanicien poids lourds": "Technical Trades & Engineering",
    "mecanicien installateur": "Technical Trades & Engineering",
    "frigoriste": "Technical Trades & Engineering",
    "refrigeration": "Technical Trades & Engineering",
    "specialise refrigeration": "Technical Trades & Engineering",
    "specialise froid": "Technical Trades & Engineering",
    "tourneur fraiseur": "Technical Trades & Engineering",
    "fraiseur": "Technical Trades & Engineering",
    "automaticien": "Technical Trades & Engineering",
    "programmeur plc": "Technical Trades & Engineering",
    "conducteur travaux": "Technical Trades & Engineering",
    "conducteur site": "Technical Trades & Engineering",
    "conducteur machine": "Technical Trades & Engineering",
    "conducteur engins": "Technical Trades & Engineering",
    "ingenieur surveillance": "Technical Trades & Engineering",
    "ingenieur projet": "Technical Trades & Engineering",
    "ingenieur qaqc": "Technical Trades & Engineering",
    "ingenieur calcul": "Technical Trades & Engineering",
    "bureau detude": "Technical Trades & Engineering",
    "bureau detudes": "Technical Trades & Engineering",
    "ingenieur daffaires detudes": "Technical Trades & Engineering",
    "dessinateur": "Technical Trades & Engineering",
    "dessinateurmetreurprojeteur": "Technical Trades & Engineering",
    "dessinateurs": "Technical Trades & Engineering",
    "dessinatrices": "Technical Trades & Engineering",
    "dessinateur projeteur": "Technical Trades & Engineering",
    "projeteur": "Technical Trades & Engineering",
    "metreur": "Technical Trades & Engineering",
    "urbaniste": "Technical Trades & Engineering",
    "architecte": "Technical Trades & Engineering",
    "modeleur bim": "Technical Trades & Engineering",
    "preparateur production plans maquettes bim": "Technical Trades & Engineering",
    "energie solaire": "Technical Trades & Engineering",
    "solaire": "Technical Trades & Engineering",
    "ingenieur detudes": "Technical Trades & Engineering",
    "btp": "Technical Trades & Engineering",
    "construction": "Technical Trades & Engineering",
    "genie civil": "Technical Trades & Engineering",
    "dao": "Technical Trades & Engineering",
    "ingenieur detude vrd": "Technical Trades & Engineering",
    "ingenieur daffaire technique": "Technical Trades & Engineering",
    "ingenieur tele propsecteurcom": "Technical Trades & Engineering",
    "ingenieur rf broadcast": "Technical Trades & Engineering",
    "ingenieur radio design": "Technical Trades & Engineering",

    # ─────────────────────────────────────────────
    # MAINTENANCE
    # ─────────────────────────────────────────────
    "maintenance": "Maintenance",
    "maintenancier": "Maintenance",
    "maintenance industriel": "Maintenance",
    "maintenance industrielle": "Maintenance",
    "maintenance entretien": "Maintenance",
    "maintenance travaux": "Maintenance",
    "maintenance materiel medical": "Maintenance",
    "maintenance suivi projets": "Maintenance",
    "maintenance outillage": "Maintenance",
    "maintenance coordinator": "Maintenance",
    "maintenance project officer": "Maintenance",
    "referent technique maintenance": "Maintenance",
    "gestionnaire maintenance": "Maintenance",
    "pole maintenance": "Maintenance",
    "planification maintenance": "Maintenance",
    "technicien maintenance": "Maintenance",
    "sav": "Maintenance",
    "service apres": "Maintenance",
    "specialise sav": "Maintenance",
    "sav experimente": "Maintenance",
    "sav numerique": "Maintenance",
    "bosch service atelier": "Maintenance",
    "atelier mecanique": "Maintenance",
    "atelier": "Maintenance",
    "techniciens maintenance": "Maintenance",

    # ─────────────────────────────────────────────
    # HOSPITALITY & FOOD SERVICE
    # ─────────────────────────────────────────────
    "serveur": "Hospitality & Food Service",
    "serveuse": "Hospitality & Food Service",
    "restaurant": "Hospitality & Food Service",
    "restauration": "Hospitality & Food Service",
    "hotellerie": "Hospitality & Food Service",
    "hotel": "Hospitality & Food Service",
    "matre dhotel": "Hospitality & Food Service",
    "maitre dhotel": "Hospitality & Food Service",
    "maitre salle": "Hospitality & Food Service",
    "matre salle": "Hospitality & Food Service",
    "receptionniste": "Hospitality & Food Service",
    "night auditor": "Hospitality & Food Service",
    "gouvernante": "Hospitality & Food Service",
    "housekeeping": "Hospitality & Food Service",
    "bagagiste": "Hospitality & Food Service",
    "barman": "Hospitality & Food Service",
    "barmaid": "Hospitality & Food Service",
    "commis salle": "Hospitality & Food Service",
    "commis bar": "Hospitality & Food Service",
    "hotesse daccueil": "Hospitality & Food Service",
    "hote": "Hospitality & Food Service",
    "blanchisserie": "Hospitality & Food Service",
    "lingere couturiere": "Hospitality & Food Service",
    "plongeur cuisine": "Hospitality & Food Service",
    "cuisinier": "Hospitality & Food Service",
    "cuisiniere": "Hospitality & Food Service",
    "cuisinierpatissier": "Hospitality & Food Service",
    "patissier": "Hospitality & Food Service",
    "patissiers": "Hospitality & Food Service",
    "patissiercuisinier": "Hospitality & Food Service",
    "commis patissier": "Hospitality & Food Service",
    "commis patisserie": "Hospitality & Food Service",
    "boulanger": "Hospitality & Food Service",
    "boulangers": "Hospitality & Food Service",
    "boulanger patissier": "Hospitality & Food Service",
    "pizzaiolo": "Hospitality & Food Service",
    "adjoint restaurant": "Hospitality & Food Service",
    "voyages": "Hospitality & Food Service",
    "travel consultant": "Hospitality & Food Service",
    "forfaitiste": "Hospitality & Food Service",
    "tourisme": "Hospitality & Food Service",
    "dagence voyage": "Hospitality & Food Service",
    "reservation": "Hospitality & Food Service",
    "reservations": "Hospitality & Food Service",
    "billetterie": "Hospitality & Food Service",

    # ─────────────────────────────────────────────
    # RETAIL & MERCHANDISING
    # ─────────────────────────────────────────────
    "caissier": "Retail & Merchandising",
    "caissiere": "Retail & Merchandising",
    "caissiercaissiere": "Retail & Merchandising",
    "caissierefacturiere": "Retail & Merchandising",
    "libre service": "Retail & Merchandising",
    "merchandiser": "Retail & Merchandising",
    "merchandiseur": "Retail & Merchandising",
    "employe libre service": "Retail & Merchandising",
    "element libre service": "Retail & Merchandising",
    "vente libre service": "Retail & Merchandising",
    "vendeurs conseils": "Retail & Merchandising",
    "vendeurs conseil": "Retail & Merchandising",
    "vendeur conseil": "Retail & Merchandising",
    "vendeurs materiaux construction": "Retail & Merchandising",
    "polyvalent magasin": "Retail & Merchandising",
    "reponsable magasin": "Retail & Merchandising",
    "responsables magasin": "Retail & Merchandising",
    "boutique": "Retail & Merchandising",
    "rayon": "Retail & Merchandising",
    "cosmetiques": "Retail & Merchandising",
    "haut niveau": "Retail & Merchandising",
    "egerie ambassadrice": "Retail & Merchandising",

    # ─────────────────────────────────────────────
    # CONTENT WRITING & TRANSLATION
    # ─────────────────────────────────────────────
    "redacteur": "Content Writing & Translation",
    "redacteurrice": "Content Writing & Translation",
    "redacteurtrice": "Content Writing & Translation",
    "redacteurs": "Content Writing & Translation",
    "redactrice": "Content Writing & Translation",
    "correcteur": "Content Writing & Translation",
    "correcteurtrice": "Content Writing & Translation",
    "relecteur": "Content Writing & Translation",
    "relecteurrelectrice": "Content Writing & Translation",
    "transcripteur": "Content Writing & Translation",
    "transcripteurs": "Content Writing & Translation",
    "traducteur": "Content Writing & Translation",
    "interprete": "Content Writing & Translation",
    "copywriter": "Content Writing & Translation",
    "ghostwriter": "Content Writing & Translation",
    "journaliste": "Content Writing & Translation",
    "documentaliste": "Content Writing & Translation",
    "editeur contenus": "Content Writing & Translation",
    "lecteur correcteur": "Content Writing & Translation",
    "annotateur franais": "Content Writing & Translation",
    "annotateur anglophone": "Content Writing & Translation",
    "collaborateurstrices experimentees transcription": "Content Writing & Translation",

    # ─────────────────────────────────────────────
    # EDUCATION & TRAINING
    # ─────────────────────────────────────────────
    "professeur": "Education & Training",
    "enseignant": "Education & Training",
    "enseignante": "Education & Training",
    "enseignants": "Education & Training",
    "institutrice": "Education & Training",
    "instituteur": "Education & Training",
    "formateur": "Education & Training",
    "formatrice": "Education & Training",
    "formateurtrices": "Education & Training",
    "formateurs": "Education & Training",
    "coach formateur": "Education & Training",
    "concepteur pedagogique": "Education & Training",
    "concepteur modules": "Education & Training",
    "operationnel pedagogique": "Education & Training",
    "conseiller pedagogique": "Education & Training",
    "conseiller principal deducation": "Education & Training",
    "directeur ecole primaire": "Education & Training",
    "directeur publication": "Education & Training",
    "vie scolaire": "Education & Training",
    "scolaire polyvalent": "Education & Training",
    "psychologue clinicien": "Education & Training",
    "partenariats secteur formation": "Education & Training",
    "centre formation": "Education & Training",
    "formation": "Education & Training",

    # ─────────────────────────────────────────────
    # HEALTH & MEDICAL
    # ─────────────────────────────────────────────
    "medecin": "Health & Medical",
    "pharmacien": "Health & Medical",
    "pharmacienne": "Health & Medical",
    "pediatre": "Health & Medical",
    "infirmiere": "Health & Medical",
    "biologiste": "Health & Medical",
    "laborantin": "Health & Medical",
    "laborantin": "Health & Medical",
    "laborantincoloriste": "Health & Medical",
    "aide labo": "Health & Medical",
    "technicienne biologie": "Health & Medical",
    "technicienne laboratoire": "Health & Medical",
    "delegue medical": "Health & Medical",
    "dieteticien": "Health & Medical",
    "masseuse": "Health & Medical",
    "estheticienne": "Health & Medical",
    "cosmetologue": "Health & Medical",
    "cosmetologie": "Health & Medical",
    "dispatcher medical": "Health & Medical",
    "techniciens securite alimentaire": "Health & Medical",
    "biomedical": "Health & Medical",

    # ─────────────────────────────────────────────
    # AGRICULTURE & ENVIRONMENT
    # ─────────────────────────────────────────────
    "agronome": "Agriculture & Environment",
    "agronomie": "Agriculture & Environment",
    "ingenieurs techniciens agricoles": "Agriculture & Environment",
    "paysagiste": "Agriculture & Environment",
    "jardinier": "Agriculture & Environment",
    "jardinier pepinieriste": "Agriculture & Environment",
    "forestier": "Agriculture & Environment",
    "plantation": "Agriculture & Environment",
    "paysannat": "Agriculture & Environment",
    "production vanille": "Agriculture & Environment",
    "production chimiste": "Agriculture & Environment",
    "auditeur agriculture biologique": "Agriculture & Environment",
    "elevage black soldier fly": "Agriculture & Environment",
    "delevage black soldier fly": "Agriculture & Environment",
    "biologiste vegetale": "Agriculture & Environment",
    "developpement durable": "Agriculture & Environment",
    "sustainability lead": "Agriculture & Environment",
    "sustainability": "Agriculture & Environment",
    "rse": "Agriculture & Environment",
    "responsabilite societale": "Agriculture & Environment",
    "climate and public finance": "Agriculture & Environment",
    "environmental and social safeguards": "Agriculture & Environment",
    "projets ruraux": "Agriculture & Environment",
    "coordonnateur demarche rse": "Agriculture & Environment",
    "social behavior change": "Agriculture & Environment",

    # ─────────────────────────────────────────────
    # SECURITY
    # ─────────────────────────────────────────────
    "securite": "Security",
    "securite surete": "Security",
    "surete groupe": "Security",
    "securite sante travail": "Security",
    "securite routiere": "Security",
    "securite ssiap": "Security",
    "ssiap": "Security",
    "securite parking": "Security",
    "gardien": "Security",
    "gardienne": "Security",
    "garde": "Security",
    "inspecteur hse": "Security",
    "inspecteur nr": "Security",
    "pole inspector": "Security",
    "gestionnaire surveillance": "Security",

    # ─────────────────────────────────────────────
    # TESTING & QA
    # ─────────────────────────────────────────────
    "testeur": "Testing & QA",
    "qa": "Testing & QA",
    "qualite": "Testing & QA",
    "qualiticien": "Testing & QA",
    "qualiticien devops": "Testing & QA",
    "qualiticien fren": "Testing & QA",
    "qaqc": "Testing & QA",
    "quality insurance": "Testing & QA",
    "qc": "Testing & QA",
    "graduate quality project": "Testing & QA",
    "expert recettage testing": "Testing & QA",
    "controleur bases donnees": "Testing & QA",

    # ─────────────────────────────────────────────
    # GIS / GEOGRAPHIC INFORMATION SYSTEMS
    # ─────────────────────────────────────────────
    "systemes information geographique": "GIS & Geomatics",
    "sig": "GIS & Geomatics",
    "geomaticien": "GIS & Geomatics",
    "geomaticien sig": "GIS & Geomatics",
    "dessinateur autocad cartographie": "GIS & Geomatics",
    "topographe": "GIS & Geomatics",
    "topographes": "GIS & Geomatics",
    "urbaniste amenagement": "GIS & Geomatics",
    "expert sig energies renouvelables": "GIS & Geomatics",
    "geologue": "GIS & Geomatics",

    # ─────────────────────────────────────────────
    # PRODUCTION & MANUFACTURING
    # ─────────────────────────────────────────────
    "production": "Production & Manufacturing",
    "operateur production": "Production & Manufacturing",
    "operateurstrices online": "Production & Manufacturing",
    "operateurs polyvalents": "Production & Manufacturing",
    "operateurs chaudiere": "Production & Manufacturing",
    "operateur machines": "Production & Manufacturing",
    "operateur machine decoupe laser": "Production & Manufacturing",
    "operateur machine bois": "Production & Manufacturing",
    "operateur extrusion": "Production & Manufacturing",
    "operateur incinerateur": "Production & Manufacturing",
    "ouvrier patissier": "Production & Manufacturing",
    "ouvrier lamineur": "Production & Manufacturing",
    "conducteur machine industrielle": "Production & Manufacturing",
    "conducteur machine automatisee": "Production & Manufacturing",
    "paoiste": "Production & Manufacturing",
    "fabrication": "Production & Manufacturing",
    "gestionnaire production": "Production & Manufacturing",
    "machinistes laveurs industriels": "Production & Manufacturing",
    "laborantincoloriste": "Production & Manufacturing",
    "laborantorin teinture": "Production & Manufacturing",
    "echantillonneur textile": "Production & Manufacturing",
    "echantillonneur": "Production & Manufacturing",
    "production textile": "Production & Manufacturing",
    "production savon": "Production & Manufacturing",
    "production broderie": "Production & Manufacturing",
    "production bougie": "Production & Manufacturing",
    "production encaustique": "Production & Manufacturing",
    "production developpement produits": "Production & Manufacturing",
    "staff production": "Production & Manufacturing",
    "ite production soufflage pet": "Production & Manufacturing",
    "chaine production": "Production & Manufacturing",
    "dop usine": "Production & Manufacturing",
    "directeur dusine": "Production & Manufacturing",
    "production maintenance prod": "Production & Manufacturing",
    "industrial engineering": "Production & Manufacturing",
    "ieindustrial engineer": "Production & Manufacturing",
    "techniciens education bien etre": "Production & Manufacturing",
    "agents production": "Production & Manufacturing",
    "siropier": "Production & Manufacturing",
    "couturier": "Production & Manufacturing",
    "crochetteuse": "Production & Manufacturing",
    "patronnier": "Production & Manufacturing",
    "sellier capitonneur": "Production & Manufacturing",

    # ─────────────────────────────────────────────
    # TELECOMMUNICATIONS
    # ─────────────────────────────────────────────
    "ingenieur tele propsecteurcom": "Telecommunications",
    "ingenieur rf broadcast": "Telecommunications",
    "ingenieur radio design": "Telecommunications",
    "ingenieur tele propsecteurcommications": "Telecommunications",
    "installation transmission": "Telecommunications",
    "fibre optique": "Telecommunications",
    "filaire": "Telecommunications",
    "reseaux physiques rrp": "Telecommunications",
    "equipements geolocalisation": "Telecommunications",
    "operateur noc": "Telecommunications",
    "deploiement it": "Telecommunications",

    # ─────────────────────────────────────────────
    # COACHING & SPORTS
    # ─────────────────────────────────────────────
    "coach": "Coaching & Sports",
    "coach sportif": "Coaching & Sports",
    "coach business": "Coaching & Sports",
    "coach carriere": "Coaching & Sports",
    "coach conduite": "Coaching & Sports",
    "coach shopify": "Coaching & Sports",
    "coach production bilingue": "Coaching & Sports",
    "coach tennis fitness": "Coaching & Sports",
    "coach musculation": "Coaching & Sports",
    "personal driver": "Coaching & Sports",
    "driver mentor": "Coaching & Sports",

    # ─────────────────────────────────────────────
    # DOMESTIC & PERSONAL SERVICES
    # ─────────────────────────────────────────────
    "femme menage": "Domestic & Personal Services",
    "femmes menage": "Domestic & Personal Services",
    "homme dentretien": "Domestic & Personal Services",
    "gouvernante femme menage": "Domestic & Personal Services",
    "garde denfants": "Domestic & Personal Services",
    "garde denfants noou": "Domestic & Personal Services",
    "noou creche": "Domestic & Personal Services",
    "noou garde": "Domestic & Personal Services",
    "gardienne denfants": "Domestic & Personal Services",
    "educatrice prescolaire": "Domestic & Personal Services",
    "educateureducatrice specialisee": "Domestic & Personal Services",
    "gens maison": "Domestic & Personal Services",
    "couple femme menage": "Domestic & Personal Services",
    "cuisinier domicile": "Domestic & Personal Services",
    "cuisiniere domicile": "Domestic & Personal Services",
    "coiffeur": "Domestic & Personal Services",

    # ─────────────────────────────────────────────
    # SPECIALIZED / NICHE
    # ─────────────────────────────────────────────
    "wash": "Specialized/Niche Roles",
    "nutrition": "Specialized/Niche Roles",
    "monitoring and evaluation": "Specialized/Niche Roles",
    "suivi evaluation": "Specialized/Niche Roles",
    "procurement officer": "Specialized/Niche Roles",
    "procurment officer": "Specialized/Niche Roles",
    "copper buyer": "Specialized/Niche Roles",
    "investment ref": "Specialized/Niche Roles",
    "fdraising officer": "Specialized/Niche Roles",
    "fdraising": "Specialized/Niche Roles",
    "creative": "Specialized/Niche Roles",
    "createur plateforme": "Specialized/Niche Roles",
    "compositeur": "Specialized/Niche Roles",
    "bien etre": "Specialized/Niche Roles",
    "governance locale": "Specialized/Niche Roles",
    "gestion connaissances": "Specialized/Niche Roles",
    "climate": "Specialized/Niche Roles",
    "grad data analyste": "Specialized/Niche Roles",
    "graduate data analyste": "Specialized/Niche Roles",
    "jior due diligence": "Specialized/Niche Roles",
    "head of scm": "Specialized/Niche Roles",
    "head of transformation": "Specialized/Niche Roles",
    "strategic learning lead": "Specialized/Niche Roles",
    "transformation innovation": "Specialized/Niche Roles",
    "plateforme digitale": "Specialized/Niche Roles",
    "contre maitre": "Specialized/Niche Roles",
    "valideur": "Specialized/Niche Roles",
}

MISSPELLING_FIXES = {
    # Typos fréquents dans les titres de poste
    "propsecteur": "prospecteur",
    "prospecteurtravail": "prospecteur travail",
    "prospecteurphone": "prospecteur phone",
    "prospecteurphonique": "prospecteur phonique",
    "prospecteurprospecteur": "prospecteur prospecteur",
    "prospecteurvente": "prospecteur vente",
    "prospecteurcom": "prospecteur com",
    "prospecteurcommications": "prospecteur communications",
    "commity": "community manager",
    "commication": "communication",
    "commication interne": "communication interne",
    "qaulite": "qualite",
    "comptabilte": "comptabilite",
    "suplly": "supply",
    "accotant": "accountant",
    "accoting": "accounting",
    "accot": "account",
    "stagaire": "stagiaire",
    "desystemes information geographiquener": "designer systemes information geographique",
    "webdesystemes information geographiquener": "web designer systemes information geographique",
    "uxui desystemes information geographiquener": "uxui designer",
    "uiux desystemes information geographiquener": "uiux designer",
    "desystemes information geographiquen graphique": "designer graphique",
    "fdraising": "fundraising",
    "commautaire": "communautaire",
    "commaute": "communaute",
    "reseaux sociaux bilingue": "reseaux sociaux bilingue",
    "prospecteurtravail": "prospecteur travail",
    "ingenieur tehnicien eau": "ingenieur technicien eau",
    "responsabilte": "responsabilite",
    "experimente": "experimente",
    "confirme": "confirme",
    "bilingue frang": "bilingue francais",
    "recaudit": "recrutement audit",
    "admi": "administrateur",
}
GEOGRAPHIC_MARKERS = {
    "tana": "Antananarivo",
    "antananarivo": "Antananarivo",
    "tamatave": "Tamatave",
    "antsirabe": "Antsirabe",
    "fianarantsoa": "Fianarantsoa",
    "diego": "Diego Suarez",
}